{% set version = "0.25.0" %}

package:
  name: django-leaflet
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-leaflet/django-leaflet-{{ version }}.tar.gz
  sha256: 73a09861a0f9de22dabbc25f5bab0c4246ee9831d315c04aa61ced47efc38084

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - django

test:
  commands:
    - python -c "import django; from django.conf import settings; settings.configure(INSTALLED_APPS=['leaflet']); django.setup(); import leaflet;"

about:
  home: https://github.com/makinacorpus/django-leaflet
  license: LGPL
  license_family: LGPL
  license_file: LICENSE
  summary: 'django-leaflet allows you to use Leaflet in your Django projects.'
  description: |
    Main purposes of having a python package for the Leaflet Javascript library::
    - Install and enjoy ;
    - Do not embed Leaflet assets in every Django project ;
    - Enjoy geometry edition with Leaflet form widget ;
    - Control apparence and settings of maps from Django settings (e.g. at deployment) ;
    - Reuse Leaflet map initialization code (e.g. local projections) ;
    note:: django-leaflet is compatible with django-geojson fields, which allow handling 
    geographic data without spatial database.
  doc_url: https://django-leaflet.readthedocs.io/en/latest/
  dev_url: https://github.com/makinacorpus/django-leaflet

extra:
  recipe-maintainers:
    - xmnlab
